version: '3'

services:
  nginx:
    image: nginx:1.23.4
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php-fpm

  php-fpm:
    build: ./docker/php-fpm
    volumes:
     - ./src:/var/www/html
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command:
      mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=user
      - PMA_PASSWORD=password
    depends_on:
      - mysql
    ports:
      - 8080:80